CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(160) NOT NULL,
  role ENUM('APPLICANT','AFFILIATE','ADMIN','MANAGEMENT') NOT NULL DEFAULT 'APPLICANT',
  status ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS countries (
  code CHAR(2) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  currency VARCHAR(10) NOT NULL
);
CREATE TABLE IF NOT EXISTS states (
  id INT AUTO_INCREMENT PRIMARY KEY,
  country_code CHAR(2) NOT NULL,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT fk_state_country FOREIGN KEY (country_code) REFERENCES countries(code) ON DELETE CASCADE,
  INDEX idx_state_country (country_code)
);
CREATE TABLE IF NOT EXISTS affiliate_applications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  application_number VARCHAR(32) NOT NULL UNIQUE,
  applicant_type ENUM('INDIVIDUAL','COMPANY') NOT NULL,
  legal_name VARCHAR(180) NOT NULL,
  company_number VARCHAR(80) NULL,
  country_code CHAR(2) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  address_line1 VARCHAR(255) NULL,
  address_line2 VARCHAR(255) NULL,
  address_line3 VARCHAR(255) NULL,
  postcode VARCHAR(20) NULL,
  town VARCHAR(100) NULL,
  state VARCHAR(100) NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'MYR',
  website_url VARCHAR(500) NULL,
  social_url VARCHAR(500) NULL,
  market_focus ENUM('SINGAPORE','MALAYSIA','BOTH') NOT NULL,
  audience_description TEXT NOT NULL,
  promotion_method TEXT NOT NULL,
  id_doc_path VARCHAR(500) NULL,
  holding_id_path VARCHAR(500) NULL,
  flag_id_doc_unclear TINYINT(1) NOT NULL DEFAULT 0,
  flag_holding_id_unaccepted TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('SUBMITTED','UNDER_REVIEW','INFORMATION_REQUIRED','CORRECTION_REQUIRED','PENDING_MANAGEMENT_APPROVAL','APPROVED','REJECTED','SUSPENDED','TERMINATED','RETRACTED','RETRACTION_ACKNOWLEDGED') NOT NULL DEFAULT 'SUBMITTED',
  affiliate_code VARCHAR(32) NULL UNIQUE,
  upline_affiliate_code VARCHAR(32) NULL,
  assigned_reviewer_id BIGINT UNSIGNED NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at TIMESTAMP NULL,
  decision_note TEXT NULL,
  is_test TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_application_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_application_reviewer FOREIGN KEY (assigned_reviewer_id) REFERENCES users(id),
  INDEX idx_application_status (status), INDEX idx_application_submitted (submitted_at)
);
CREATE TABLE IF NOT EXISTS application_status_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  application_id BIGINT UNSIGNED NOT NULL,
  from_status VARCHAR(40) NULL,
  to_status VARCHAR(40) NOT NULL,
  changed_by BIGINT UNSIGNED NULL,
  public_message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_history_application FOREIGN KEY (application_id) REFERENCES affiliate_applications(id),
  CONSTRAINT fk_history_user FOREIGN KEY (changed_by) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS onboarded_customers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  affiliate_id BIGINT UNSIGNED NOT NULL,
  customer_name VARCHAR(180) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(50) NULL,
  package_name VARCHAR(150) NOT NULL,
  package_count INT UNSIGNED NOT NULL DEFAULT 1,
  annual_value_myr DECIMAL(12,2) NOT NULL DEFAULT 60000.00,
  signed_date DATE NOT NULL,
  status ENUM('SIGNED','ACTIVE','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  is_test TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_customer_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliate_applications(id) ON DELETE CASCADE,
  INDEX idx_customer_affiliate (affiliate_id)
);
CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  csrf_token_hash CHAR(64) NOT NULL DEFAULT '',
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_session_expiry (expires_at)
);
-- T-510 (F-15): fixed-window rate-limit counters, MySQL-backed (see lib/rate-limit.ts).
CREATE TABLE IF NOT EXISTS rate_limit_attempts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  identifier VARCHAR(255) NOT NULL,
  route VARCHAR(64) NOT NULL,
  window_start TIMESTAMP NOT NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 1,
  UNIQUE KEY uq_rate_limit_window (identifier, route, window_start),
  INDEX idx_rate_limit_window_start (window_start)
);
-- T-510 follow-on fix: single-use, time-limited password reset tokens
-- (see app/api/forgot-password/route.ts, app/api/reset-password/route.ts).
CREATE TABLE IF NOT EXISTS password_resets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  requested_ip VARCHAR(64) NULL,
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_password_reset_expiry (expires_at)
);
CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  actor_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id VARCHAR(80) NOT NULL,
  event_data JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id), INDEX idx_audit_entity (entity_type,entity_id)
);
CREATE TABLE IF NOT EXISTS system_settings (
  setting_key VARCHAR(80) PRIMARY KEY,
  setting_value VARCHAR(255) NOT NULL,
  description VARCHAR(255) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS deal_pipeline (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  affiliate_id BIGINT UNSIGNED NOT NULL,
  deal_code VARCHAR(32) NOT NULL UNIQUE,
  customer_name VARCHAR(180) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(50) NULL,
  package_name VARCHAR(150) NOT NULL,
  package_count INT UNSIGNED NOT NULL DEFAULT 1,
  contract_value_myr DECIMAL(12,2) NOT NULL DEFAULT 60000.00,
  status ENUM(
    'LEAD_SUBMITTED',
    'QUALIFIED',
    'PROPOSAL_SENT',
    'SUSPENDED_EFFORT',
    'ABORTED',
    'CONTRACT_SIGNED',
    'INVOICED',
    'PARTIAL_COLLECTED',
    'FULLY_COLLECTED',
    'UNCOLLECTIBLE'
  ) NOT NULL DEFAULT 'LEAD_SUBMITTED',
  status_note TEXT NULL,
  suspended_reason TEXT NULL,
  aborted_reason TEXT NULL,
  extension_days_granted INT UNSIGNED NOT NULL DEFAULT 0,
  is_force_closed TINYINT(1) NOT NULL DEFAULT 0,
  force_closed_at TIMESTAMP NULL,
  force_closed_reason TEXT NULL,
  status_before_force_closure VARCHAR(32) NULL,
  appeal_status ENUM('NONE', 'APPEAL_SUBMITTED', 'APPEAL_APPROVED', 'APPEAL_REJECTED') NOT NULL DEFAULT 'NONE',
  appeal_reason TEXT NULL,
  appeal_submitted_at TIMESTAMP NULL,
  appeal_adjudicated_at TIMESTAMP NULL,
  appeal_adjudication_notes TEXT NULL,
  signed_date DATE NULL,
  invoice_number VARCHAR(64) NULL,
  invoice_target ENUM('PROSPECT', 'AFFILIATE') NOT NULL DEFAULT 'PROSPECT',
  invoiced_at TIMESTAMP NULL,
  is_test TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_deal_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliate_applications(id) ON DELETE CASCADE,
  INDEX idx_deal_status (status),
  INDEX idx_deal_affiliate (affiliate_id)
);
CREATE TABLE IF NOT EXISTS deal_funnel_steps (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  deal_id BIGINT UNSIGNED NOT NULL,
  from_stage VARCHAR(50) NULL,
  to_stage VARCHAR(50) NOT NULL,
  step_title VARCHAR(180) NOT NULL,
  affiliate_notes TEXT NOT NULL,
  submitted_by_user_id BIGINT UNSIGNED NOT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  admin_review_status ENUM('PENDING_REVIEW', 'ACKNOWLEDGED', 'RETURNED_FOR_REVIEW') NOT NULL DEFAULT 'PENDING_REVIEW',
  admin_remarks TEXT NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  is_immutable TINYINT(1) NOT NULL DEFAULT 1,
  is_test TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_step_deal FOREIGN KEY (deal_id) REFERENCES deal_pipeline(id) ON DELETE CASCADE,
  CONSTRAINT fk_step_submitter FOREIGN KEY (submitted_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_step_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id),
  INDEX idx_step_deal (deal_id),
  INDEX idx_step_status (admin_review_status)
);
CREATE TABLE IF NOT EXISTS deal_closure_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  deal_id BIGINT UNSIGNED NOT NULL,
  action_type ENUM('FORCED_CLOSURE', 'APPEAL_SUBMITTED', 'EXTENSION_GRANTED', 'APPEAL_REJECTED') NOT NULL,
  days_extended INT NOT NULL DEFAULT 0,
  action_notes TEXT NOT NULL,
  performed_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_log_deal FOREIGN KEY (deal_id) REFERENCES deal_pipeline(id) ON DELETE CASCADE,
  CONSTRAINT fk_log_user FOREIGN KEY (performed_by_user_id) REFERENCES users(id),
  INDEX idx_closure_log_deal (deal_id)
);
CREATE TABLE IF NOT EXISTS deal_collections (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  deal_id BIGINT UNSIGNED NOT NULL,
  invoice_number VARCHAR(64) NOT NULL,
  invoice_total_myr DECIMAL(12,2) NOT NULL,
  collected_amount_myr DECIMAL(12,2) NOT NULL,
  bank_receipt_ref VARCHAR(100) NOT NULL,
  proof_media_path VARCHAR(500) NULL,
  locked_direct_rate_pct DECIMAL(5,2) NOT NULL DEFAULT 10.00,
  locked_upline_l1_rate_pct DECIMAL(5,2) NOT NULL DEFAULT 3.00,
  locked_upline_l2_rate_pct DECIMAL(5,2) NOT NULL DEFAULT 1.50,
  approval_status ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING_APPROVAL',
  approved_by BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  approval_remarks TEXT NULL,
  is_immutable TINYINT(1) NOT NULL DEFAULT 0,
  collection_date DATE NOT NULL,
  is_final_collection TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  is_test TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_coll_deal FOREIGN KEY (deal_id) REFERENCES deal_pipeline(id) ON DELETE CASCADE,
  CONSTRAINT fk_coll_approver FOREIGN KEY (approved_by) REFERENCES users(id),
  INDEX idx_coll_deal (deal_id),
  INDEX idx_coll_approval (approval_status)
);
CREATE TABLE IF NOT EXISTS payout_batches (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  batch_code VARCHAR(32) NOT NULL UNIQUE,
  beneficiary_affiliate_id BIGINT UNSIGNED NOT NULL,
  total_amount_myr DECIMAL(12,2) NOT NULL,
  advice_count INT UNSIGNED NOT NULL,
  manual_bank_tx_ref VARCHAR(100) NOT NULL,
  bank_name VARCHAR(100) NULL,
  bank_account_number VARCHAR(100) NULL,
  payout_notes TEXT NULL,
  disbursed_by BIGINT UNSIGNED NOT NULL,
  disbursed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_test TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_batch_affiliate FOREIGN KEY (beneficiary_affiliate_id) REFERENCES affiliate_applications(id) ON DELETE CASCADE,
  CONSTRAINT fk_batch_user FOREIGN KEY (disbursed_by) REFERENCES users(id),
  INDEX idx_batch_beneficiary (beneficiary_affiliate_id)
);
CREATE TABLE IF NOT EXISTS payment_advices (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  advice_number VARCHAR(32) NOT NULL UNIQUE,
  collection_id BIGINT UNSIGNED NOT NULL,
  deal_id BIGINT UNSIGNED NOT NULL,
  beneficiary_affiliate_id BIGINT UNSIGNED NOT NULL,
  beneficiary_type ENUM('DIRECT_AFFILIATE', 'UPLINE_L1', 'UPLINE_L2') NOT NULL,
  rate_percentage DECIMAL(5,2) NOT NULL,
  collection_amount_base_myr DECIMAL(12,2) NOT NULL,
  commission_amount_myr DECIMAL(12,2) NOT NULL,
  payout_status ENUM('PENDING_DISBURSEMENT', 'PAID', 'CANCELLED') NOT NULL DEFAULT 'PENDING_DISBURSEMENT',
  paid_at TIMESTAMP NULL,
  manual_bank_tx_ref VARCHAR(100) NULL,
  payout_notes TEXT NULL,
  payout_batch_id BIGINT UNSIGNED NULL,
  is_immutable TINYINT(1) NOT NULL DEFAULT 1,
  is_test TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_adv_collection FOREIGN KEY (collection_id) REFERENCES deal_collections(id) ON DELETE CASCADE,
  CONSTRAINT fk_adv_deal FOREIGN KEY (deal_id) REFERENCES deal_pipeline(id) ON DELETE CASCADE,
  CONSTRAINT fk_adv_affiliate FOREIGN KEY (beneficiary_affiliate_id) REFERENCES affiliate_applications(id) ON DELETE CASCADE,
  CONSTRAINT fk_adv_batch FOREIGN KEY (payout_batch_id) REFERENCES payout_batches(id) ON DELETE SET NULL,
  UNIQUE KEY uq_adv_collection_beneficiary_type (collection_id, beneficiary_affiliate_id, beneficiary_type),
  INDEX idx_adv_beneficiary (beneficiary_affiliate_id),
  INDEX idx_adv_status (payout_status),
  INDEX idx_adv_batch (payout_batch_id)
);
CREATE TABLE IF NOT EXISTS affiliate_profile_updates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  application_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('PENDING_APPROVAL','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING_APPROVAL',
  full_name VARCHAR(160) NOT NULL,
  applicant_type ENUM('INDIVIDUAL','COMPANY') NOT NULL,
  legal_name VARCHAR(180) NOT NULL,
  company_number VARCHAR(80) NULL,
  country_code CHAR(2) NOT NULL,
  state VARCHAR(100) NULL,
  town VARCHAR(100) NULL,
  postcode VARCHAR(20) NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'MYR',
  address_line1 VARCHAR(255) NULL,
  address_line2 VARCHAR(255) NULL,
  address_line3 VARCHAR(255) NULL,
  phone VARCHAR(50) NOT NULL,
  website_url VARCHAR(500) NULL,
  social_url VARCHAR(500) NULL,
  market_focus ENUM('SINGAPORE','MALAYSIA','BOTH') NOT NULL,
  audience_description TEXT NOT NULL,
  promotion_method TEXT NOT NULL,
  id_doc_path VARCHAR(500) NULL,
  holding_id_path VARCHAR(500) NULL,
  upline_affiliate_code VARCHAR(32) NULL,
  admin_remarks TEXT NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_profile_update_app FOREIGN KEY (application_id) REFERENCES affiliate_applications(id) ON DELETE CASCADE,
  CONSTRAINT fk_profile_update_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_profile_update_status (status),
  INDEX idx_profile_update_app (application_id)
);
CREATE TABLE IF NOT EXISTS packages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  package_name VARCHAR(150) NOT NULL UNIQUE,
  package_code VARCHAR(50) NOT NULL UNIQUE,
  unit_price_myr DECIMAL(12,2) NOT NULL,
  billing_cycle VARCHAR(50) NOT NULL DEFAULT 'per annum',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT IGNORE INTO packages (package_name, package_code, unit_price_myr, billing_cycle, is_active)
VALUES
  ('FolioDesk 5-User Annual License', 'FD-5USER-ANNUAL', 60000.00, 'per annum', 1),
  ('FolioDesk 3-Year 5-User License', 'FD-3YR-5USER', 158000.00, '3-year term', 1),
  ('Unlimited Master Reseller License', 'FD-MASTER-RESELLER', 1200000.00, 'per annum', 1),
  ('Design Partner Perpetual License', 'FD-DESIGN-PARTNER-LIFETIME', 300000.00, 'perpetual (max 10)', 1);

-- Maker-checker approval queue (plan §7.2). Generic table shared by all four
-- in-scope maker-checker flows: collection approval, payout disbursement,
-- affiliate application approval, and force-closure appeal adjudication.
CREATE TABLE IF NOT EXISTS maker_checker_requests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  request_type ENUM(
    'COLLECTION_APPROVAL',
    'PAYOUT_DISBURSEMENT',
    'APPLICATION_APPROVAL',
    'CLOSURE_APPEAL_ADJUDICATION'
  ) NOT NULL,
  entity_type VARCHAR(60) NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  action_payload JSON NOT NULL,
  status ENUM('PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  submitted_by BIGINT UNSIGNED NOT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_by BIGINT UNSIGNED NULL,
  decided_at TIMESTAMP NULL,
  decision_notes TEXT NULL,
  is_immutable TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_mc_submitter FOREIGN KEY (submitted_by) REFERENCES users(id),
  CONSTRAINT fk_mc_decider FOREIGN KEY (decided_by) REFERENCES users(id),
  CONSTRAINT chk_mc_separation CHECK (decided_by IS NULL OR decided_by <> submitted_by),
  INDEX idx_mc_status (status),
  INDEX idx_mc_type (request_type),
  INDEX idx_mc_entity (entity_type, entity_id)
);
